services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "order_db"
      POSTGRES_USER: "order_user"
      POSTGRES_PASSWORD: "order_password"
    ports:
      - "5432:5432"
